baseURL = "https://newswriter.ai/news"
languageCode = 'en-us'
title = 'Newswriter Business and Technology News'
theme = 'newsjockey-hugo'
disablePathToLower = false
removePathAccents = false
uglyURLs = false
canonifyURLs = true

# IMPORTANT: Comment out or remove permalink configuration to allow frontmatter URL control
# [permalinks]
#   news = "/:year:month/:slug/"

[params]
  description = "Newswriter.ai Curated Business and Technology News"
  author = 'Newswriter Staff'
  mainSections = ["news"]
  newsSection = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Disable default sitemap generation
disableKinds = ["sitemap"]

[outputFormats]
  [outputFormats.SitemapXML]
    mediaType = "application/xml"
    baseName = "sitemap"
    isPlainText = true
    notAlternative = true

# Configure outputs for different page types
[outputs]
  home = ["HTML", "SitemapXML"]
  section = ["HTML", "SitemapXML"]      
