baseURL = "https://newswriter.ai"
languageCde = 'en-us'
title = 'Newswriter Business and Technology News'
theme = 'newsjockey-hugo'

[params]
  description = "Newswriter.ai Curated Business and Technology News"
  author = "Newswriter Staff"

  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Disable default sitemap generation
disableKinds = ["sitemap"]

[outputFormats]
  [outputFormats.sitemap]
    mediaType = "application/xml"
    baseName = "sitemap"
    isPlainText = true
    protocol = "xml://"

[outputs]
  home = ["HTML"]
  section = ["HTML", "sitemap"]
  page = ["HTML", "sitemap"]
