baseURL = "https://newswriter.ai/news"
languageCde = 'en-us'
title = 'Newswriter Business and Technology News'
theme = 'newsjockey-hugo'

[params]
  description = "Newswriter.ai Curated Business and Technology News"
  author = "Newswriter Staff"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Disable default sitemap generation
disableKinds = ["sitemap"]
